{'name': 'Hospital Management Odoo 18',
 'version': '18.0.1.0.5',
 'category': 'Services',
 'summary': 'This Module Helps to Manage Patients Records, Doctors Details,\n'
            '     Lab Management , Employee Management etc.',
 'description': 'The hospital management module can be used to handle \n'
                '     the day-to-day activities of the hospital. Managing patient '
                'scheduling, \n'
                '     making patient ID cards, creating patient lab test results, and '
                'adding \n'
                '     doctors, patients, prescriptions, vaccines, etc. are all made '
                'easier \n'
                '     with the help of this module. This app offers a different '
                'dashboards for \n'
                '     different users.',
 'author': 'Cybrosys Techno Solutions',
 'company': 'Cybrosys Techno Solutions',
 'maintainer': 'Cybrosys Techno Solutions',
 'website': 'https://www.cybrosys.com',
 'depends': ['website', 'hr', 'stock', 'sale_management'],
 'data': ['security/base_hospital_management_groups.xml',
          'security/hospital_enterprise_security.xml',
          'security/doctor_allocation_security.xml',
          'security/doctor_slot_security.xml',
          'security/patient_lab_test_security.xml',
          'security/ir.model.access.csv',
          'data/ir_sequence_data.xml',
          'data/hospital_enterprise_sequences.xml',
          'data/ir_cron_data.xml',
          'data/website_data.xml',
          'views/menu_views.xml',
          'views/inpatient_surgery_views.xml',
          'views/hospital_bed_views.xml',
          'views/blood_bank_views.xml',
          'views/contra_indication_views.xml',
          'views/booking_success_templates.xml',
          'views/hospital_building_views.xml',
          'views/hospital_degree_views.xml',
          'views/doctor_allocation_views.xml',
          'views/hr_employee_views.xml',
          'views/hospital_inpatient_views.xml',
          'views/hospital_insurance_views.xml',
          'views/hospital_laboratory_views.xml',
          'views/patient_lab_test_views.xml',
          'views/lab_test_views.xml',
          'views/lab_test_result_views.xml',
          'views/medicine_brand_views.xml',
          'views/hospital_outpatient_views.xml',
          'views/res_partner_views.xml',
          'views/hospital_enterprise_views.xml',
          'views/patient_portal_templates.xml',
          'views/hospital_vaccination_views.xml',
          'views/product_template_views.xml',
          'views/room_facility_views.xml',
          'views/patient_card_templates.xml',
          'views/booking_success_templates.xml',
          'views/doctor_specialization_views.xml',
          'views/hospital_pharmacy_views.xml',
          'views/hospital_ward_views.xml',
          'views/patient_booking_templates.xml',
          'views/patient_room_views.xml',
          'views/lab_test_line_views.xml',
          'report/res_partner_reports.xml',
          'report/lab_test_line_reports.xml'],
 'demo': ['demo/hr_job_demo.xml'],
 'assets': {'web.assets_frontend': ['base_hospital_management/static/src/js/prescription.js',
                                    'base_hospital_management/static/src/js/website_page.js'],
            'web.assets_backend': ['base_hospital_management/static/src/css/hospital_kanban_cards.css',
                                   'base_hospital_management/static/src/css/doctor_dashboard.css',
                                   'base_hospital_management/static/src/css/reception_dashboard.css',
                                   'base_hospital_management/static/src/css/lab_dashboard.css',
                                   'base_hospital_management/static/src/css/pharmacy_dashboard.css',
                                   'base_hospital_management/static/src/css/hospital_role_dashboard.css',
                                   'base_hospital_management/static/src/xml/lab_dashboard_templates.xml',
                                   'base_hospital_management/static/src/xml/doctor_dashboard_templates.xml',
                                   'base_hospital_management/static/src/js/lab_dashboard.js',
                                   'base_hospital_management/static/src/js/doctor_dashboard.js',
                                   'base_hospital_management/static/src/xml/pharmacy_orderlines.xml',
                                   'base_hospital_management/static/src/js/pharmacy_orderlines.js',
                                   'base_hospital_management/static/src/xml/pharmacy_dashboard_templates.xml',
                                   'base_hospital_management/static/src/js/pharmacy_dashboard.js',
                                   'base_hospital_management/static/src/xml/reception_dashboard_templates.xml',
                                   'base_hospital_management/static/src/js/reception_dashboard.js']},
 'external_dependencies': {'python': ['python-barcode']},
 'images': ['static/description/banner.jpg'],
 'license': 'AGPL-3',
 'installable': True,
 'auto_install': False,
 'application': True}
