# -*- coding: utf-8 -*-
from . import account_move
from . import hospital_accounting_service
from . import hospital_accounting_dashboard
from . import hospital_inpatient_charge
from . import hospital_charge
from . import hospital_insurance
from . import res_partner
from . import lab_test
from . import lab_test_result
from . import patient_lab_test
from . import hospital_outpatient
from . import hospital_inpatient
from . import hospital_bed
from . import patient_room
from . import hr_employee
from . import account_payment
from . import hospital_patient_payments
from . import hospital_phase3_finance
from . import hospital_phase3_invoice_extensions
from . import hospital_branch
from . import hospital_phase6_finance
